### ISSUE TITLE
Critique-of-Taylor-s-Law-for-Human-Linguistic-Sequences [To Publish]

### ISSUE THREAD

**Issue by omarsar** [dair-ai/nlp_paper_summaries#33]
Got permission from @jadevaibhav to publish the following article on dair.ai's main website.

**Article:**
https://github.com/jadevaibhav/Critique-of-Taylor-s-Law-for-Human-Linguistic-Sequences/blob/master/README.md

**Tasks:**
- [x] Migrate the article to our main website repo: https://github.com/dair-ai/dair-ai.github.io/tree/master/_posts
- [x] Proofread and review and make necessary changes
- [x] Add author's information 
- [ ] Publish on the main website (dair.ai)
- [ ] Add the entry to the NLP Paper Summaries repo (let's figure out under which folder we can add it)
- [ ] Share on social media and our Slack group  

**Author's information:**

```
jadevaibhav:
  name: Vaibhav Jade
  github:  jadevaibhav
```

**Comment by manisnesan** [comment]
@omarsar - Started working on this task. I have migrated the article to the dair-ai.github.io site. Can you provide push permissions for dair-ai-github.io repository to add a remote branch & create pull request?

**Comment by omarsar** [comment]
@manisnesan I think you should have that permission already. Let me know if you still have issues with it. Thanks.

**Comment by manisnesan** [comment]
@omarsar @e-tony 

I have completed the following tasks 
[x] Migrate the article to our main website repo: https://github.com/dair-ai/dair-ai.github.io/tree/master/_posts
 [x]Proofread and review and make necessary changes
 [x]Add author's information

Pull request for dair-ai.github.io can be found [here](https://github.com/dair-ai/dair-ai.github.io/pulls)

**Comment by manisnesan** [comment]
One can able to apply the patch ( by renaming the file from txt to .patch) & following the below command 

$ git apply --check 0001-nlp_paper_summary-Issue-33-Migrated-Proof-read-the-a.patch
$ git am --signoff  0001-nlp_paper_summary-Issue-33-Migrated-Proof-read-the-a.patch

[0001-nlp_paper_summary-Issue-33-Migrated-Proof-read-the-a.txt](https://github.com/dair-ai/nlp_paper_summaries/files/4743010/0001-nlp_paper_summary-Issue-33-Migrated-Proof-read-the-a.txt)

**Comment by omarsar** [comment]
@manisnesan I will check this over the coming weekend. I am on leave this week. Thanks.

**Comment by manisnesan** [comment]
@omarsar - Thanks for the response. Enjoy the time off.

**Comment by manisnesan** [comment]
@omarsar @e-tony - Gentle reminder for a review.
